### PR TITLE
Added Spotify Embeds

### PR DESCRIPTION
**Pull request by leolabs**
When Webogram detects a Spotify Link, it will automatically insert a Spotify-embed which lets you hear the track/album/playlist

### CODE REVIEW

**Comment by zhukov** [comment]
Thanks for the PR.
There are couple issues to be fixed. Also please squash the changes into single commit: https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md#how-do-changes-suggested-on-a-pull-request.

**Comment by zhukov** [comment]
Please  squash all the changes into single commit.

**Comment by leolabs** [comment]
I couldn't manage to squash the commits. Maybe I'm using the Git shell wrong but running 'git rebase -i master' doesn't show the commits I made related to the Spotify embeds.

**Comment by leolabs** [comment]
Any idea what could be wrong?

**Comment by zhukov** [comment]
Then please submit a new PR which contains single commit and close this one.

**Comment by rjw57** [comment]
@leolabs You've made your changes in your local master branch. (For future reference, this is poor practice; the usual workflow is to branch before starting work. The reason being that one ends up confused about which ``master`` is which.) Doing ``git rebase -i origin/master`` should work if you originally cloned this repo. If you originally cloned your fork, you'll need to work out what you called the github.com/zhukov remote.

**Comment by zhukov** [comment]
@leolabs sorry, I had to commit this by myself in order to release update on time. Thanks anyway.
Good news: we'll have Spotify URLs support. Next time please follow the contributing guidelines from https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md

**Comment by leolabs** [comment]
No problem, man. Cool to know that I could contribute :smiley:

**Comment by Christilut** [comment]
Not sure if this is the right place to request this (if not, I'll move it to a new issue), but...

Can this be updated to also include Spotify URI's? Such as: spotify:track:1VLXo9vSB2kYkIjoPGOBdY

**Pull request closed without merging**
