### PR TITLE
Update to layer 62

### PR DESCRIPTION
**Pull request by stek29**
#1309.

I don't see any dangerous or breaking changes, but I'm not sure about `updates.differenceTooLong`.
Anyway, it seems to work fine for me.

### CODE REVIEW

**Comment by stek29** [comment]
About `differenceTooLong`: I guess behaviour stated at [Telegram Site](https://core.telegram.org/api/updates#obtaining-differences) was changed. It says:
>If the updates.differenceSlice constructor is returned in the response, the full difference was too large to be received by the client all at once. The intermediate status, intermediate_state, must be saved on the client and the query must be repeated, using the intermediate status as the current status.

But now it may return `updates.differenceTooLong` I guess, and app would have to call `updates.getDifference` set to some value.

**Comment by zhukov** [comment]
@stek29 There is no point in merging just schema update into master. We need to have new features support.

**Comment by stek29** [comment]
@zhukov New Features support depend on this, and I'm already working on Pinned Chats support.

**Comment by zhukov** [comment]
Will wait for the PR with full layer support. Closing for now.

**Comment by stek29** [comment]
Btw, iirc this has an issue with schema being not in JSON but rather in JS -- it has trailing comma somewhere.
Not sure that's even worth noting.

**Pull request closed without merging**
