### PR TITLE
Check code value when country was selected. Fix #650

### LINKED ISSUE #650: Sign in, try remove code and select country
* Open login page
* Select country
* Delete the code
* Re-select country

screen

### PR DESCRIPTION
**Pull request by ArtemFitiskin**
Is it ok?

### CODE REVIEW

**Comment by zhukov** [comment]
I wrote a comment in the issue: https://github.com/zhukov/webogram/issues/650#issuecomment-69559810

**Comment by zhukov** [comment]
4 commits are too much for such a small fix. Please merge them as described here: https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md#how-do-changes-suggested-on-a-pull-request.

**Comment by ArtemFitiskin** [comment]
Oh, sorry i missed it in CONTRIBUTING.md.

Updated.

**Comment by zhukov** [comment]
Thank you for the PR.

**Pull request merged**
