### PR TITLE
Add Catalan language

### PR DESCRIPTION
**Pull request by Ecron**
Catalan translation from [Transifex](https://www.transifex.com/projects/p/telegram-web/language/ca/) is ready to be merged into Webogram. It's completely checked, even some angular locale errors fixed (I recommend to get the JSON file from [Transifex Catalan team](https://www.transifex.com/projects/p/telegram-web/resource/en-usjson/l/ca/download/for_use/), although I will keep the JSON file updated).

### CODE REVIEW

**Comment by stek29** [comment]
@Ecron Yup, it looks like it can't be merged until other apps add Catalan too. See #1263.

**Comment by stek29** [comment]
@zhukov ping

**Comment by Ecron** [comment]
@stek29 Yep, I don't even update this PR due to the negative to expand Telegram's native languages. The moment I see they open the door to it, I'll update the files in this request.

**Comment by stek29** [comment]
I highly doubt they will

**Comment by trufae** [comment]
:(

**Pull request closed without merging**
