### PR TITLE
Changed misleading text button from 'Edit' to 'Select'

### PR DESCRIPTION
**Pull request by Akronix**
In my opinion, the header button saying "Edit" on the top corner right can be misleading as [some users has reported earlier.](#1258).
It can make people think that they are gonna edit the chat info, the user profile, the last message or something like that, while, in fact, this button just opens a "Selection messages" mode.
Moreover I think we have too many "Edit" buttons in webogram for different things: "Edit profile", "Edit chat", "Edit contact", "Edit group" and, [recently added](https://github.com/zhukov/webogram/commit/5e855779b94e5812d80cebbea17a328fdf77ded9), "Edit message" 

Feel free to correct me If I've inferred some bad translation or if there are some other parts of the code that should be corrected.

### CODE REVIEW

**Comment by stek29** [comment]
Locales shouldn't be edited here.

**Comment by Akronix** [comment]
OK, any opinion about the motivation of the PR?

**Comment by stek29** [comment]
@Akronix I think it is unclear, but I doubt it will (and should) be changed: "Edit" button is usually used to go into "Edit mode", which is made to edit whole history, not just one message.

**Comment by Akronix** [comment]
But isn't a "selection mode" actually? From that mode you can do "Forward" which is not editing at all.
What you do is selecting messages to do something with them afterwards, like when you select files in the file explorer to copy, delete or rename them.

**Comment by stek29** [comment]
I guess it's because of iOS: Edit button activates selection/editing mode in almost any app

**Comment by Akronix** [comment]
Well but this isn't iOS...

**Comment by stek29** [comment]
@Akronix *shrug*

**Comment by Ryuno-Ki** [comment]
In Telegram Desktop I enter the edit/select mode by “lassoing” the messages, i.e. I _select_ them.

**Comment by Akronix** [comment]
And then, you can do the actions that -the current named- "edit" button allows you to do. So, what's your point @Ryuno-Ki

**Comment by Ryuno-Ki** [comment]
It was thought as an argument pro renaming edit button to select.

**Comment by zhukov** [comment]
Thanks for the PR, but I did it in a right way.

**Pull request closed without merging**
