### PR TITLE
Create tr-tr.json

### PR DESCRIPTION
**Pull request by ali-demirtas**
I completed the Turkish translation file. Hopefully, in a short time it is added to the site.

### CODE REVIEW

**Comment by ali-demirtas** [comment]
Why don't you add this language?

**Comment by ali-demirtas** [comment]
@zhukov

**Comment by ali-demirtas** [comment]
@stek29 @zhukov

**Comment by stek29** [comment]
translations are not managed on GitHub. they were managed on transifex, but it's gone now.
So, can't help much. Not closing because I wonder what Igor would say.

**Comment by zhukov** [comment]
We don't maintain translation here anyway. Need to support native localization platform.

**Pull request closed without merging**
