### PR TITLE
Fix #814  Add sticker suggestion panel

### LINKED ISSUE #814: Emojis don't suggest stickers
When I put an emoji (both from the emoji tab and from the :whatever: access) it does not suggest any related sticker. Is it a bug or intented?

If it's intended, could you implement it? It may not be that hard..

Thanks a lot!

### PR DESCRIPTION
**Pull request by lhyqy5**
Fix #814 

preview
preview

### CODE REVIEW

**Comment by Akronix** [comment]
what happened with this?

**Comment by lhyqy5** [comment]
@Akronix
I removed this PR because for a long time nobody cares
if you really want this,you can use my [host version](https://tg.loli.ski/) ,or get [my code](https://github.com/lhyqy5/webogram/tree/mywork) to  host your own

**Comment by Akronix** [comment]
what about merging it with upstream web.telegram.org @zhukov ??

**Comment by Akronix** [comment]
ping @zhukov

**Comment by stek29** [comment]
The implementation is not angular friendly.

**Pull request closed without merging**
