### PR TITLE
Parity with tdesktop

### PR DESCRIPTION
**Pull request by goodmind**
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl

Same file name with tdesktop

### CODE REVIEW

**Comment by bartist** [comment]
Can you indicate how this will change functionality?
Changing a filename will/should have impact somewhere on how the code works, so can you state where it will have impact?

**Comment by goodmind** [comment]
@bartist this file never referenced in code, so functionality not affected

**Comment by bartist** [comment]
Ow, can you indicate why this change is necessary? or is it pure uniformity?

**Comment by goodmind** [comment]
@bartist yes, just uniformity with tdesktop

**Comment by bartist** [comment]
Okay, thanks for the clarification :)

**Comment by stek29** [comment]
Isn't that file outdated and redurant? It's not used in Webogram, schema is in JSON inside of config.js anyways.

**Comment by zhukov** [comment]
@stek29 no, it isn't.

**Comment by zhukov** [comment]
See no point here, file contents is different, Webogram's one doesn't include mtproto, has the same formatting as on https://core.telegram.org/schema

**Comment by stek29** [comment]
@zhukov but what is it used for? JSON schema generation?

**Comment by zhukov** [comment]
@stek29 nope, it's for development. it's like very short documentation.

**Comment by stek29** [comment]
@zhukov :D
https://github.com/stek29/tl-schema
https://stek29.rocks/tl-schema/l66

**Comment by goodmind** [comment]
@zhukov why you want to keep txt extension?

**Comment by stek29** [comment]
@goodmind it's not just about txt extension.
I've spent last weekend digging through schema's in both webogram and tdesktop, and they differ a bit because of how these apps work with them -- TDesktop has mtp layer too, for example.

Also, why do you want this change in first place? What's the point? Does it worth breaking the links?

**Comment by goodmind** [comment]
@stek29 because I merged Type Language highlight to https://github.com/github/linguist/pull/3593

**Comment by stek29** [comment]
@goodmind Oh, it makes sense now :)

**Pull request closed without merging**
