### PR TITLE
fix #457 change URL-regexp

### LINKED ISSUE #457: Link conversion from pasted URL forgets trailing character
When Telegram converts a pasted URL like

http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano)

to a link, it leaves the trailing parenthesis out and produces this

http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano

Thus making the link invalid.

### PR DESCRIPTION
**Pull request by ArtemFitiskin**

### CODE REVIEW

**Comment by zhukov** [comment]
And thanks for the PR!
If you manage to fix these couple issues, I will merge these changes and include them into 0.4.0 which is coming very soon.

**Comment by zhukov** [comment]
@ArtemFitiskin I guess, I will implement this tomorrow by myself, if you are not going to update the PR.

**Comment by ArtemFitiskin** [comment]
@zhukov I have some doubts about your idea to use a TLD-list, because someone  can be used in Telegram links with TLD from local network, such as the internal correspondence between the two admins of some organization with top level domain like .mybigorg, really do we have any reason do not highlight such links?

**Comment by ArtemFitiskin** [comment]
Also, I think that regex:

```javascript
/[12]?\d?\d\.[12]?\d?\d\.[12]?\d?\d\.[12]?\d?\d/
```

highlights too much of incorrect IP like 00.00.00.00 or 256.256.256.256. I replaced existing part for match IP with [that regex](https://github.com/sindresorhus/ip-regex/blob/master/index.js#L3) by @sindresorhus. Is it OK? I'm update the PR.

**Comment by ArtemFitiskin** [comment]
Also, I think that regex:

```javascript
/[12]?\d?\d\.[12]?\d?\d\.[12]?\d?\d\.[12]?\d?\d/
```

highlights too much of incorrect IP like 00.00.00.00 or 256.256.256.256. I replaced existing part for match IP with [that regex](https://github.com/sindresorhus/ip-regex/blob/master/index.js#L3) by @sindresorhus. Is it OK?

**Comment by ArtemFitiskin** [comment]
I can not rebase this branch with upstream master, can you help me?

**Comment by zhukov** [comment]
Yep, I like the new version. Will merge it.

**Comment by zhukov** [comment]
Thank you for the contribution. I've added some fixes: links without protocol tried to open as relative path and mailto: protocol was not supported.

**Pull request merged**
