### PR TITLE
Disable instructions for firefox os

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by stek29** [comment]
Why should this be merged?
And if instructions are incorrect, why are you just trying to comment out them instead of removing/rewriting.

**Comment by kskarthik** [comment]
Ok, I removed completely

**Comment by stek29** [comment]
1) rebaseandsqua.sh
2) Why would you remove it? What's the issue?

**Comment by kskarthik** [comment]
Since firefox os is no more.

**Comment by stek29** [comment]
\*facepalm\*

**Comment by zhukov** [comment]
Sorry, no plans to remove FxOS mentions yet.

**Pull request closed without merging**
