### PR TITLE
Unused variables #1564

### PR DESCRIPTION
**Pull request by azzimuth**
Solves #1564

### CODE REVIEW

**Comment by stek29** [comment]
I guess cdc0b78 is not meant to be in this PR :)

**Comment by azzimuth** [comment]
Yeah, right. I don't know why that file was included...

**Comment by azzimuth** [comment]
And the Files tab includes only the intended file, app/js/lib/mtproto.js

**Comment by zhukov** [comment]
@azzimuth I'm a bit concerned about extra commits. Can you please rebase and squash changes?

**Comment by azzimuth** [comment]
Closing this PR and opening another as I had to remove my fork (was to messy to sort out my old commits).

**Pull request closed without merging**
