### PR TITLE
Add admins to channels and supergroups

### PR DESCRIPTION
**Pull request by stek29**
Partially based on #952, was rechecked and lots of issues were fixed.

Also has no conflicts with master branch, huh.

### CODE REVIEW

**Comment by zhukov** [comment]
Well the PR is nice, thanks. But we need to add list of admins as well.
I think nicer UX would be TDesktop-like: add "Manage admins" link in group profile, with a list of admins and button to add new administrator.

**Comment by stek29** [comment]
What if we sort member list so all admins are on top?

**Comment by stek29** [comment]
Ok, that's what I did for now.
Has serious issues, and a lot of work needs to be done:
1) ManageUsers should be rewritten with custom directive, and should use some kind of scrollable wrap like contacts or countries. For now it looks terrible, especially with Desktop layout.
2) Infinite loading would be nice
3) "Everyone is admin" and "Who can add new users" are missing
4) Doesn't handle updating and reloading so well, especially in normal groups. I'm not really sure what to do with it.
5) Current way of working with switches is really terrible. `ng-class="class(user)"`! It also creates so much unnecessary watches. I'm not so familiar with angular, and the only other way I think of is adding some kind of `type` property to each user (with on/off/ + disabled), and changing it with `switch`... I don't know XD
6) It would be a good idea to change descriptions for user from showing last seen to showing by whom user was banned and when (or any other custom description formatted with i18n)

The most serious issue is that I don't know Angular :(

(Oh, and it can be tested at https://stek29.github.io/webogram ofc)

**Comment by stek29** [comment]
Just... Just look at this.
image

**Comment by Ryuno-Ki** [comment]
> ManageUsers should be rewritten with custom directive

How would you imagine the usage of that directive? Shall it get replaced with native DOM elements?

**Comment by stek29** [comment]
@Ryuno-Ki have a look at Contacts/Country/Chat selection modals

**Comment by stek29** [comment]
@Ryuno-Ki What do you think about `5`? What's the proper way to do it?
I need three cases: on, off, on+disabled (off+disabled isn't used).
There's also no need to watch them, only change on click. But they must be initialized first...

**Comment by lifehome** [comment]
This is so interesting, that you can add unblocked users(don't leave the "Blocked Users" modal) back to the banlist. I wonder if possible to manually add users to the banlist, without adding them into a group?

**Comment by Ryuno-Ki** [comment]
For those three cases you'll likely need a select (listing all combinations) or a checkbox (for disabled state) + radio (on/off).

**Comment by lifehome** [comment]
I wonder why this PR is not merging into the repo branches?

**Comment by stek29** [comment]
@lifehome It's not finished because I'm having exams now + don't really know angular well.

**Pull request closed without merging**
