### PR TITLE
Improved url parsing. Fix #457

### LINKED ISSUE #457: Link conversion from pasted URL forgets trailing character
When Telegram converts a pasted URL like

http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano)

to a link, it leaves the trailing parenthesis out and produces this

http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano

Thus making the link invalid.

### PR DESCRIPTION
**Pull request by ArtemFitiskin**
Try to improve URL parsing (previous - #684). Hope this helps you solve problems pulled hard. 

Issues list: 
- [x] #697 
- [x] #692 
- [x] #690 
- [x] #457 

Also, inspired by this ideas:

* https://github.com/zhukov/webogram/issues/692#issuecomment-74249062
* https://github.com/zhukov/webogram/issues/690#issuecomment-74245849

P. S. It is main part of my test:
```
Yes:
http://telegram.org
telegram.org
TeLeGrAm.oRg
http://telegram.ololo
mailto:name@example.com
name@example.com
127.0.0.1
149.154.167.51
http://149.154.167.51
http://google.com/?file=file.extension
http://www.contoso.com/test.html
http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano)
http://foo.com/blah_(wikipedia)_blah#cite-1
http://foo.com/unicode_(✪)_in_parens
http://foo.bar/?q=Test%20URL-encoded%20stuff
http://مثال.إختبار
http://例子.测试
http://उदाहरण.परीक्षा
name@example.ololo

Be careful:
http:// shouldfail.com
"http://yandex.ru/ololo/"
'http://yandex.ru/ololo/'
[http://yandex.ru/ololo/]
{http://yandex.ru/ololo/}
Plese, try http://telegram.org.
(http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano))
(Something like http://foo.com/blah_blah_(wikipedia))
text http://telegram.org text
http://example.com/something?with,commas,in,url, but not at end

No:
API.messages.readHistory
file.extension
telegram.ololo
00.00.00.00
256.256.256.256
ya@telegram
http://
http://.
http://..
http://../
http://?
http://??
http://??/
http://#
http://##
http://##/
```

### CODE REVIEW

**Comment by zhukov** [comment]
Very nice PR, thanks again. Going to test it ASAP

**Comment by ArtemFitiskin** [comment]
I just tried your ideas and updated the PR.

**Comment by zhukov** [comment]
I have made some corrections and merged this to master. Hope you are OK with it.
Very helpful PR  :+1:

**Comment by ArtemFitiskin** [comment]
noo

## Desc

Let me explain the logic behind the parenthesis processing in URI (I tried to use GitHub editor’s logic as much as I can understand it):
1) the number of opening and closing brackets are equal - nothing needs to be done, regardless of the URL context URL it will look allright;
2) the number of closing brackets exceeds the number of opening ones - eliminate unnecessary closing brackets at the end of the URL, until their number becomes equal to the number of opening brackets. Thus we are trying to select the most correct URL from the context.
3) the number of opening brackets exceeds the number of closing - in this case the best solution is to eliminate all closing parentheses at all end of the URL., because we cannot add any parentheses, we also cannot figure out how many of the closing parenthesis at the end must be included in incorrect URL.

## My dirty example

### Text:
```
(http://it.wikipedia.org/wiki/Linea_(M4_(metropolitana_di_(Milano)_fgfg)
(http://it.wikipedia.org/wiki/Linea_(M4_(metropolitana_di_(Milano)_fgfg)))
(http://it.wikipedia.org/wiki/Linea_(M4_(metropolitana_di_(Milano)_fg)fg)))
(http://it.wikipedia.org/wiki/Linea_(M4_(metropolitana_di_(Milano)_fgfg))
(http://it.wikipedia.org/wiki/Linea_(M4_metropolitana))gfgfg
((http://it.wikipedia.org/wiki/Linea_(M4_(metropolitana_di_(Milano))_fgfg))
(http://it.wikipedia.org/wiki/Linea_(M4_((((metropolitana_di_(Milano)_fgfg))
(http://it.wikipedia.org/wiki/Linea_(M4_((((metropolitana_di_(Milano_fgfg)
```

Yes, it looks kinda strange, but show difference.

### Screenshoots: 

* GitHub
github

* Exist 
now

* Temp
temp

**Comment by zhukov** [comment]
I got this. Sorry for that, I have reverted this logic. Now the example is working like GitHub one. Is that OK?

**Comment by zhukov** [comment]
Current master is available live on zhukov.github.io/webogram and will be released to stable locations soon.

**Comment by ArtemFitiskin** [comment]
I think that all right at now. Maybe it's time to close dependent issues?

**Comment by zhukov** [comment]
Yep. Will release the update to web.telegram.org today.

**Comment by danger89** [comment]
Thanks everyone :+1:

**Pull request merged**
