### PR TITLE
Fixed typo in german translation

### PR DESCRIPTION
**Pull request by mattelacchiato**
"Schliessen" is not correct: http://www.duden.de/rechtschreibung/schlieszen

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Well, in Swiss Standard German you would write it actually "Schliessen" …

**Comment by auchri** [comment]
@Ryuno-Ki but it's de-DE --> German (Germany)

**Comment by Ryuno-Ki** [comment]
Good point!

**Comment by mattelacchiato** [comment]
I would suggest to create a new translation for de-ch as described in https://github.com/zhukov/webogram/blob/master/app/js/locales/README.md

**Comment by stek29** [comment]
I thought all translations are maintained [on transifex](https://www.transifex.com/telegram/telegram-web/).
And as usual, you can use "Ask a question" button which is located in settings to report this issue.

Btw, why no one creates an issue before pull request in this repo? 
IMO it's much better to create an issue, describe everything and then just make commit/PR with `Fixes #issue-number` and brief explanation.

**Comment by mattelacchiato** [comment]
Okay, this is my first contribution to webogram. Just tell me what kind of process I've to follow just to fix this typo...

**Comment by stek29** [comment]
I'm not sure, but try replying to telegram on twitter.

**Comment by zhukov** [comment]
Hi,
no need to contact on Twitter. I will pass this issue to German translator. Thanks

**Pull request closed without merging**
