### PR TITLE
Add W3C web app manifest

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
Please do not mix Chrome extension manifest (https://goo.gl/7z3gvm) and W3C web app manifest (https://goo.gl/CQoUdw).

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
We need app icon in SVG (app/img/icons/icon.svg), PNG 192x192 (app/img/icons/icon192.png) and PNG 512x512 (app/img/icons/icon512.png).

**Comment by stek29** [comment]
> We need app icon in SVG

[Have you even looked at repository contents?](https://github.com/zhukov/webogram/blob/master/app/img/Telegram.svg)

**Comment by FluorescentHallucinogen** [comment]
@stek29
> [Have you even looked at repository contents?](https://github.com/zhukov/webogram/blob/master/app/img/Telegram.svg)

Have you even looked this file?

It's not the app icon.

**Comment by stek29** [comment]
@FluorescentHallucinogen Sorry :\

**Comment by Ryuno-Ki** [comment]
> Please do not mix Chrome extension manifest (https://developer.chrome.com/extensions/manifest) and W3C web app manifest (https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/).

I released the links from the shortener. Yw

**Comment by FluorescentHallucinogen** [comment]
@zhukov, PTAL.

**Comment by stek29** [comment]
That icon isn't the one Webogram uses.
Please, don't switch to it like TDesktop did.

**Comment by FluorescentHallucinogen** [comment]
@stek29, please explain what you mean? :-/

**Comment by stek29** [comment]
@FluorescentHallucinogen the icon you added is used by iOS and macOS apps (and TDesktop Alpha)
While Android, TDesktop Stable and Webogram have a slight different icon

**Comment by FluorescentHallucinogen** [comment]
@stek29, what the difference?

This repo contains 3 different kinds of icons: 2 round and 1 square. Please see:

https://github.com/zhukov/webogram/blob/master/app/img/icons/icon16.png
https://github.com/zhukov/webogram/blob/master/app/img/icons/icon32.png
https://github.com/zhukov/webogram/blob/master/app/img/icons/icon60.png
https://github.com/zhukov/webogram/blob/master/app/img/icons/icon64.png
https://github.com/zhukov/webogram/blob/master/app/img/icons/icon90.png
https://github.com/zhukov/webogram/blob/master/app/img/icons/icon120.png
https://github.com/zhukov/webogram/blob/master/app/img/icons/icon128.png

https://github.com/zhukov/webogram/blob/master/app/img/Telegram72.png
https://github.com/zhukov/webogram/blob/master/app/img/Telegram72_2x.png

https://github.com/zhukov/webogram/blob/master/app/img/iphone_home120.png

BTW, Webogram uses the first kind of icons for https://github.com/zhukov/webogram/blob/master/app/favicon.ico.

I've also used the first kind of icons, that Webogram uses for Chrome and Firefox extensions (packaged apps).

If you have the _right_ icon, you can help by posting it here or sending it to me.

BTW, I can design the new app icon specifically for Webogram using Material Design spec. :wink:

**Comment by zhukov** [comment]
Thanks for the PR. I've added SVG icon, 192 and 512px versions.

**Comment by FluorescentHallucinogen** [comment]
Please see my comments on 9ce0bb0aeafe6708d0d7c9fdce3442064126bfd9.

**Pull request closed without merging**
