### PR TITLE
I added Thai language.

### PR DESCRIPTION
**Pull request by slwt2002**
I added Thai language.
I'm going to make a web page for Thai people.
Thank You

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
@zhukov has responded to similiar PRs with the following in the past:

> Sorry, all the translation updates should go through Transifex: https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md#localization
> 
> We don't have Thai at the moment, but you can send a request there. This case you'll be notified when we the language will be added.

**Comment by slwt2002** [comment]
I sent a request to https://www.transifex.com/telegram/telegram-web/  
But no reply yet.
Thank You

**Comment by Ryuno-Ki** [comment]
Thanks for the engagement! I was trying to speed things up.

Be aware that it can take days before you get an reaction by the maintainer @zhukov

**Comment by zhukov** [comment]
Sorry, all translations stuff in not maintained by me. See https://core.telegram.org/translating_telegram

**Pull request closed without merging**
